name: Purge
on:
  schedule:
    - cron: 0 6 * * *
  workflow_dispatch:

defaults:
  run:
    shell: pwsh
    working-directory: scripts

env:
  JCMS_GITHUBSPCLIENTID: ${{ secrets.JCMS_GITHUBSPCLIENTID }}
  JCMS_GITHUBSPCLIENTSECRET: ${{ secrets.JCMS_GITHUBSPCLIENTSECRET }}
  JCMS_SUBSCRIPTIONID: ${{ secrets.JCMS_SUBSCRIPTIONID }}
  JCMS_TENANTID: ${{ secrets.JCMS_TENANTID }}
  JCMS_CREDS:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: scripts
          fetch-depth: 1

      - run: . ./shared.ps1

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ env.JCMS_CREDS }}

      - name: Delete resources
        run: . ./200_purge.ps1
